service: ex-auth
runtime: nodejs
env: flex

beta_settings:
  cloud_sql_instances: "stoked-reality-284921:europe-west2:extream"

env_variables:
  CLOUD_SQL_USERNAME: $CLOUD_SQL_USERNAME
  CLOUD_SQL_DATABASE: $CLOUD_SQL_DATABASE
  CLOUD_SQL_PASSWORD: $CLOUD_SQL_PASSWORD
  CLOUD_SQL_INSTANCE: $CLOUD_SQL_INSTANCE
  EXTREAM_FROM_ADDESS: $EXTREAM_FROM_ADDESS
  SECURE_KEY: $SECURE_KEY
  TEST_VAR: 'someKey'
  ADMIN_EMAIL: $ADMIN_EMAIL
  SENDGRID_API_KEY: $SENDGRID_API_KEY
  SENDGRID_INVITEE_TEMPLATE_ID: $SENDGRID_INVITEE_TEMPLATE_ID
  SENDGRID_PASSWORDLESS_LOGIN_LINK_TEMPLATE_ID: $SENDGRID_PASSWORDLESS_LOGIN_LINK_TEMPLATE_ID
  SENDGRID_CLIENT_SIGNUP_TEMPLATE_ID: $SENDGRID_CLIENT_SIGNUP_TEMPLATE_ID
