service: ex-auth
runtime: nodejs
env: flex

beta_settings:
  cloud_sql_instances: stoked-reality-284921:europe-west2:extream

env_variables:
  DB_USER: "postgres"
  DB_NAME: "ex-manage"
  DB_PASS: "4cDzu3f1K1qjq1zp4cDzu3f1K1qjq1zp"
  INSTANCE_CONNECTION_NAME: stoked-reality-284921:europe-west2:extream