service: ex-auth
runtime: nodejs14

env_variables:
  CLOUD_SQL_USERNAME: $CLOUD_SQL_USERNAME
  CLOUD_SQL_DATABASE: $CLOUD_SQL_DATABASE
  CLOUD_SQL_PASSWORD: $CLOUD_SQL_PASSWORD
  CLOUD_SQL_INSTANCE: $CLOUD_SQL_INSTANCE
  EXTREAM_FROM_ADDRESS: $EXTREAM_FROM_ADDRESS
  SECURE_KEY: $SECURE_KEY
  ADMIN_EMAIL: $ADMIN_EMAIL
  SENDGRID_API_KEY: $SENDGRID_API_KEY
  SENDGRID_INVITEE_TEMPLATE_ID: $SENDGRID_INVITEE_TEMPLATE_ID
  SENDGRID_PASSWORDLESS_LOGIN_LINK_TEMPLATE_ID: $SENDGRID_PASSWORDLESS_LOGIN_LINK_TEMPLATE_ID
  SENDGRID_CLIENT_SIGNUP_TEMPLATE_ID: $SENDGRID_CLIENT_SIGNUP_TEMPLATE_ID

liveness_check:
  path: "/status"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 300

readiness_check:
  path: "/status"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 600
