# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1.4.3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      
#     - uses: actions/gcloud/auth@master
#       env:
#         GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
        
#     - uses: actions/gcloud/cli@master
#       with:
#         args: "app deploy --quiet --project=APP_ENGINE_PROJECT_NAME"

    - name: Google Cloud Platform (GCP) CLI - gcloud
      uses: actions-hub/gcloud@307.0.0
      env:
        PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
        APPLICATION_CREDENTIALS: ${{secrets.GCLOUD_CREDENTIALS}}
      with:
        args: app deploy app.yaml
